version = 1
SPDX-PackageName = "harbour-lovegame"
SPDX-PackageSupplier = "Mirian Margiani <mixosaurus+ichthyo@pm.me>"
SPDX-PackageDownloadLocation = "https://codeberg.org/ichthyosaurus/harbour-lovegame"

[[annotations]]
path = "translations/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022-2024 harbour-lovegame translations contributors"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "libs/opal-translations/opal-about/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2020-2022 opal-about contributors"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "libs/opal-docs/**.qch"
precedence = "aggregate"
SPDX-FileCopyrightText = "2020-2022 opal contributors"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "libs/module_opal-**.txt"
precedence = "aggregate"
SPDX-FileCopyrightText = "2020-2022 opal contributors"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "rpm/harbour-**.spec"
precedence = "aggregate"
SPDX-FileCopyrightText = "Mirian Margiani"
SPDX-License-Identifier = "GPL-3.0-or-later"
SPDX-FileComment = "This file is generated from [this file's name].yaml and shares copyright with it."

[[annotations]]
path = ["icons/**", "qml/images/**", "dist/harbour-**.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Mirian Margiani"
SPDX-License-Identifier = "CC-BY-SA-4.0"
SPDX-FileComment = "These files are generated from the sources at icon-src/*."

[[annotations]]
path = "icon-src/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Mirian Margiani"
SPDX-License-Identifier = "CC-BY-SA-4.0"
SPDX-FileComment = "These files contain proper Dublin Core licensing metadata."

[[annotations]]
path = "TRANSLATORS.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "translations contributors"
SPDX-License-Identifier = "GPL-3.0-or-later"
